import {useState,useEffect} from "react";
import {Ic,Av,Brand,PEOPLE,cx} from "./rap_kit";
const sections:Record<string,string[][]>={
Community:[["feed","Home","home"],["network","My network","users"],["groups","Groups","users"],["messenger","Messages","chat"],["notifications","Notifications","bell"],["profile","My profile","user"]],
Careers:[["jobs","Discover jobs","briefcase"],["recs","Recommended for you","target"],["applications","My applications","file"],["saved","Saved jobs","bookmark"],["dash","Career overview","chart"],["companies","Explore companies","building"],["onboarding","Career preferences","settings"]],
Workspace:[["workspace","Overview","layers"],["projects","Project board","board"],["taskmarket","Task offers","inbox"],["submissions","Submissions","file"],["worklog","Work log","clock"],["contracts","Contracts","file"],["earnings","Payments","wallet"],["reviews","Reviews","star"],["quality","Quality review","code"]],
Hiring:[["codash","Hiring overview","chart"],["cojobs","Job postings","briefcase"],["postjob","Post a job","plus"],["candidates","Candidates","users"],["engineers","Discover talent","search"],["coprofile","Company profile","building"],["contracts","Contracts","file"],["copayments","Payments","wallet"]],
Account:[["settings","Account settings","settings"],["security","Security & verification","shield"],["profile","Profile & visibility","user"],["help","Help center","question"]],
Admin:[["admin","Platform overview","chart"],["adminusers","People & access","users"],["adminjobs","Job moderation","briefcase"],["reports","Content reports","flag"],["verifications","Verification queue","shieldcheck"],["audit","Audit trail","history"],["sync","Job sources","layers"],["aiusage","AI usage","spark"],["health","System health","bolt"],["flags","Feature availability","settings"]]};
export function AppShell({r,go,mods,children}:any){const [menu,setMenu]=useState("");const [q,setQ]=useState("");const [state,setState]=useState("Ready");const [role,setRole]=useState(()=>sessionStorage.getItem("rap-demo-role")||"engineer");
useEffect(()=>{setMenu("");setState("Ready")},[r]);
let section=Object.keys(sections).find(s=>sections[s].some(x=>x[0]===r))||"Community";
if(["jobdetail","work"].includes(r))section="Careers";if(["company","engineer","talent"].includes(r))section="Hiring";if(["contractsign"].includes(r))section="Workspace";if(r==="group")section="Community";
const nav=(rows:string[][])=>rows.map(([path,label,icon])=><button key={path} onClick={()=>go(path)} className={cx("rap-nav",r===path&&"selected")} aria-current={r===path?"page":undefined}><span className="rap-nav-icon"><Ic n={icon} s={22}/></span><span>{label}</span></button>);
const primary=[["feed","Home","home","Community"],["network","My network","users","Network"],["jobs","Jobs","briefcase","Careers"],["workspace","Workspace","board","Workspace"],["codash","Hiring","building","Hiring"]];
return <div className="rap-app"><header className="rap-top"><div className="rap-brand-search"><button aria-label="Remote AI home" onClick={()=>go("feed")}><Brand s={42}/></button><form onSubmit={e=>{e.preventDefault();sessionStorage.setItem("rap-search",q);go("search")}}><Ic n="search" s={19}/><input aria-label="Search Remote AI" placeholder="Search Remote AI" value={q} onChange={e=>setQ(e.target.value)}/></form></div><nav className="rap-primary" aria-label="Main navigation">{primary.map(([p,l,i,s])=><button key={p} title={l} onClick={()=>go(p)} className={(r===p||(section===s&&r!=="network"))?"active":""}><Ic n={i} s={26}/><span>{l}</span></button>)}</nav><div className="rap-tools">{[["waffle","Menu","pages"],["chat","Messages","messenger"],["bell","Notifications","notifications"]].map(([i,l,p])=><button key={p} aria-label={l} title={l} onClick={()=>p==="pages"?setMenu(menu?"":"pages"):go(p)}><Ic n={i} s={21}/></button>)}<button aria-label="Your account" onClick={()=>setMenu(menu?"":"account")}><Av name="Gokul Raj" s={40}/></button></div></header>
<aside className="rap-sidebar"><div className="rap-side-title">{section==="Community"?<button className="rap-person" onClick={()=>go("profile")}><Av name="Gokul Raj" s={38}/><b>Gokul Raj</b></button>:<><h1>{section}</h1><button title="Settings" aria-label="Section settings" onClick={()=>go("settings")}><Ic n="settings"/></button></>}</div>{nav(sections[section])}<div className="rap-divider"/><h3 className="rap-side-label">Your shortcuts</h3>{nav(section==="Community"?[["dash","My career","briefcase"],["workspace","My workspace","board"],["codash","Hire a team","building"]]:[["feed","Community home","home"],["network","My network","users"],["groups","My groups","users"]])}<button className="rap-more" onClick={()=>setMenu("pages")}><Ic n="waffle" s={18}/>Explore all pages</button><footer><button onClick={()=>go("privacy")}>Privacy</button> · <button onClick={()=>go("terms")}>Terms</button> · <button onClick={()=>go("help")}>Help</button><p>Remote AI Platform · Design preview</p></footer></aside>
<main className={cx("rap-main",r==="feed"&&"rap-main-feed")}><div className="rap-content" key={r}>{state==="Ready"?children:<div className="rap-state"><Ic n={state==="Error"?"flag":state==="Access denied"?"lock":"inbox"} s={42}/><h1>{state==="Loading"?"Loading your workspace…":state==="Empty"?"Nothing here yet":state==="Error"?"Something went wrong":"Access restricted"}</h1><p>{state==="Error"?"We couldn’t load the latest information. Please try again.":"Your workspace information will appear here when it is available."}</p><button className="rap-button" onClick={()=>setState("Ready")}>Return to preview</button></div>}</div></main>
{r==="feed"&&<aside className="rap-right"><h3>Recommended opportunity</h3><button className="rap-opportunity" onClick={()=>{localStorage.setItem("rap-selected-job","1");go("jobdetail")}}><span className="rap-company-mark">N</span><b>Senior AI Platform Engineer</b><p>Northstar Cloud · Remote</p><span>View opportunity →</span></button><div className="rap-divider"/><div className="flex items-center justify-between"><h3>Contacts</h3><button aria-label="Find people" onClick={()=>go("network")}><Ic n="search" s={18}/></button></div>{PEOPLE.map(p=><button className="rap-contact" key={p.n} onClick={()=>{sessionStorage.setItem("rap-contact",p.n);go("messenger")}}><Av name={p.n} s={37} dot={p.on}/><span>{p.n}</span></button>)}</aside>}
<nav className="rap-mobile">{primary.map(([p,l,i])=><button key={p} onClick={()=>go(p)}><Ic n={i}/><span>{l}</span></button>)}</nav>
{menu&&<div className="rap-overlay" onClick={()=>setMenu("")}><div role="dialog" aria-modal="true" aria-label={menu==="pages"?"Product menu":"Your account"} className={cx("rap-menu",menu==="pages"&&"wide")} onClick={e=>e.stopPropagation()}><div className="rap-menu-head"><h2>{menu==="pages"?"Menu":"Your account"}</h2><button aria-label="Close menu" onClick={()=>setMenu("")}><Ic n="x"/></button></div>{menu==="pages"?<><div className="rap-menu-grid">{Object.entries(sections).map(([title,rows])=><section key={title}><h3>{title}</h3>{nav(rows)}</section>)}<section><h3>Joining Remote AI</h3>{nav([["login","Sign in","lock"],["register","Create an account","user"],["forgot","Account recovery","mail"],["onboarding","Engineer onboarding","spark"],["coprofile","Company setup","building"]])}</section></div><div className="rap-preview-tools"><span>Prototype state</span><select aria-label="Preview state" value={state} onChange={e=>{setState(e.target.value);setMenu("")}}>{["Ready","Loading","Empty","Error","Access denied"].map(x=><option key={x}>{x}</option>)}</select><small>Sample data · No live transactions</small></div></>:<><button className="rap-person" onClick={()=>go("profile")}><Av name="Gokul Raj" s={48}/><b>Gokul Raj</b></button><div className="rap-divider"/>{nav([["profile","View your profile","user"],["settings","Settings & privacy","settings"],["security","Security & verification","shield"],["help","Help & support","question"]])}<p className="rap-side-label">Preview workspace</p>{["engineer","company","admin"].map(x=><button key={x} className="rap-nav capitalize" onClick={()=>{setRole(x);sessionStorage.setItem("rap-demo-role",x);go(x==="company"?"codash":x==="admin"?"admin":"dash")}}>{x}{role===x&&<Ic n="check" s={18}/>}</button>)}{nav([["login","Sign out","lock"]])}</>}</div></div>}
</div>}
