name: prod
values:
  - key: base_url
    value: 'https://api.remoteaiplatform.com'
    enabled: true
    type: default
  - key: supabase_url
    value: ''
    enabled: true
    type: default
  - key: supabase_publishable_key
    value: ''
    enabled: true
    type: default
  - key: email
    value: ''
    enabled: true
    type: default
  - key: otp_code
    value: ''
    enabled: true
    type: default
  - key: role
    value: 'ENGINEER'
    enabled: true
    type: default
  - key: auto_sign_in
    value: 'false'
    enabled: true
    type: default
  - key: allow_writes
    value: 'false'
    enabled: true
    type: default
  - key: allow_destructive
    value: 'false'
    enabled: true
    type: default
  - key: max_response_ms
    value: '10000'
    enabled: true
    type: default
  - key: access_token
    value: ''
    enabled: true
    type: secret
  - key: refresh_token
    value: ''
    enabled: true
    type: secret
