"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useCreateJob } from "@/hooks/useCreateJob";

export default function NewJobPage() {
  const router = useRouter();
  const createJob = useCreateJob();
  const [form, setForm] = useState({ title: "", description: "", job_type: "project", experience_level: "mid", skills: "", budget_min: "", budget_max: "", timeline: "", remote_preference: "Worldwide remote" });
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) {
    event.preventDefault();
    const job = await createJob.mutateAsync({ ...form, skills: form.skills.split(",").map((skill) => skill.trim()).filter(Boolean), budget_min: form.budget_min ? Number(form.budget_min) : undefined, budget_max: form.budget_max ? Number(form.budget_max) : undefined });
    router.push(`/jobs/${job.id}`);
  }
  return <main className="mx-auto max-w-3xl px-4 py-8"><h1 className="text-3xl font-bold text-slate-900">Post a job or project</h1><p className="mt-2 text-slate-600">Describe the outcome. Remote AI Platform will analyze requirements and suggest a delivery plan.</p><form onSubmit={submit} className="card-enterprise mt-6 space-y-5 p-6"><label className="block text-sm font-semibold text-slate-700">Title<input required value={form.title} onChange={(e) => update("title", e.target.value)} className="input-enterprise mt-2" placeholder="Build a customer analytics platform" /></label><label className="block text-sm font-semibold text-slate-700">Description<textarea required value={form.description} onChange={(e) => update("description", e.target.value)} className="input-enterprise mt-2 min-h-36" placeholder="Describe the problem, outcomes, and responsibilities." /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700">Type<select value={form.job_type} onChange={(e) => update("job_type", e.target.value)} className="input-enterprise mt-2"><option value="full-time">Full time</option><option value="contract">Contract</option><option value="freelance">Freelance</option><option value="project">Project</option></select></label><label className="block text-sm font-semibold text-slate-700">Experience<select value={form.experience_level} onChange={(e) => update("experience_level", e.target.value)} className="input-enterprise mt-2"><option value="junior">Junior</option><option value="mid">Mid-level</option><option value="senior">Senior</option><option value="lead">Lead</option></select></label></div><label className="block text-sm font-semibold text-slate-700">Required skills<input value={form.skills} onChange={(e) => update("skills", e.target.value)} className="input-enterprise mt-2" placeholder="React, Python, PostgreSQL" /></label><div className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-semibold text-slate-700">Budget minimum<input type="number" value={form.budget_min} onChange={(e) => update("budget_min", e.target.value)} className="input-enterprise mt-2" /></label><label className="block text-sm font-semibold text-slate-700">Budget maximum<input type="number" value={form.budget_max} onChange={(e) => update("budget_max", e.target.value)} className="input-enterprise mt-2" /></label><label className="block text-sm font-semibold text-slate-700">Timeline<input value={form.timeline} onChange={(e) => update("timeline", e.target.value)} className="input-enterprise mt-2" placeholder="8 weeks" /></label></div>{createJob.isError && <p className="text-sm text-red-700">Unable to publish this job. Check your company profile and try again.</p>}<button disabled={createJob.isPending} className="button-primary" type="submit">{createJob.isPending ? "Publishing…" : "Publish and analyze"}</button></form></main>;
}
