"""Architecture sync: repository -> facts -> architecture.yaml -> draw.io -> PNG.

    python -m tools.architecture sync [--png auto|always|never]   regenerate the artifacts
    python -m tools.architecture check          fail if committed artifacts are stale
    python -m tools.architecture facts          print the discovered facts
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

import yaml

from .discover import discover
from .drawio import render
from .model import UnclassifiedError, build_model, validate_model
from .product import build_product_model, render_product

ROOT = Path(__file__).resolve().parents[2]
CATALOG = Path(__file__).parent / "catalog.yaml"
PRODUCT_CATALOG = Path(__file__).parent / "product.yaml"
OUT = ROOT / "docs/architecture"
PNG_KEY = b"drawio-sha256"
# Headless draw.io for machines without the desktop app (and for CI).
DRAWIO_IMAGE = (
    "rlespinasse/drawio-desktop-headless:v1.74.0"
    "@sha256:36f3cae50f37d4efb43890d4aaa47e018b25d062a3440cd8ecf01fdd24a7bbf8"
)
EXPORT_ARGS = ["--export", "--format", "png", "--scale", "2", "--border", "24"]

HEADER = (
    "# GENERATED by `make architecture-sync` from repository evidence -- do not edit.\n"
    "# Rules live in tools/architecture/catalog.yaml; every component lists the\n"
    "# files that prove it exists.\n"
)


def generate() -> dict[str, tuple[str, str]]:
    """Diagram name -> (model YAML, draw.io XML)."""
    catalog = yaml.safe_load(CATALOG.read_text())
    model = build_model(catalog, discover(ROOT), ROOT)
    errors = validate_model(model)
    if errors:
        raise SystemExit("Invalid architecture model:\n  " + "\n  ".join(errors))
    product = build_product_model(yaml.safe_load(PRODUCT_CATALOG.read_text()), ROOT, model)
    dump = lambda m: yaml.safe_dump(m, sort_keys=False, allow_unicode=True, width=110)  # noqa: E731
    product_header = HEADER.replace("tools/architecture/catalog.yaml; every component lists the\n# files that prove it exists.", "tools/architecture/product.yaml; screens, API domains and\n# roles are read from the code.")
    return {
        "architecture": (HEADER + dump(model), render(model)),
        "product": (product_header + dump(product), render_product(product)),
    }


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def png_source_hash(png: bytes) -> str | None:
    """The drawio hash recorded in the PNG's tEXt chunk, if any."""
    pos = 8
    while pos < len(png):
        (length,) = struct.unpack(">I", png[pos : pos + 4])
        kind = png[pos + 4 : pos + 8]
        data = png[pos + 8 : pos + 8 + length]
        if kind == b"tEXt" and data.startswith(PNG_KEY + b"\0"):
            return data[len(PNG_KEY) + 1 :].decode()
        pos += 12 + length
    return None


def _stamp_png(png: bytes, digest: str) -> bytes:
    data = PNG_KEY + b"\0" + digest.encode()
    chunk = struct.pack(">I", len(data)) + b"tEXt" + data + struct.pack(">I", zlib.crc32(b"tEXt" + data))
    return png[:33] + chunk + png[33:]  # right after the 8-byte signature + IHDR chunk


def _drawio_binary() -> str | None:
    candidates = [os.environ.get("DRAWIO_BIN"), shutil.which("drawio"), "/Applications/draw.io.app/Contents/MacOS/draw.io"]
    return next((c for c in candidates if c and Path(c).exists()), None)


def _docker_available() -> bool:
    docker = shutil.which("docker")
    return docker is not None and subprocess.run([docker, "info"], capture_output=True).returncode == 0


def can_render() -> bool:
    return _drawio_binary() is not None or _docker_available()


def render_png(name: str, drawio_text: str) -> None:
    """Export the PNG with draw.io (desktop app, else the pinned Docker image)
    and stamp it with the hash of the .drawio it was rendered from."""
    binary = _drawio_binary()
    cache = ROOT / ".cache"  # gitignored; inside the repo so Docker can mount it
    cache.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(dir=cache) as tmp:
        if binary:
            command = [binary, *(["--no-sandbox"] if sys.platform.startswith("linux") else [])]
            command += [*EXPORT_ARGS, "--output", f"{tmp}/{name}.png", str(OUT / f"{name}.drawio")]
        elif _docker_available():
            command = [
                # Chromium's renderer crashes with Docker's default 64 MB /dev/shm.
                "docker", "run", "--rm", "--shm-size=1g", "-e", "HOME=/tmp",
                "-v", f"{OUT}:/in:ro", "-v", f"{tmp}:/out", "-w", "/out",
                DRAWIO_IMAGE, *EXPORT_ARGS, "--output", f"/out/{name}.png", f"/in/{name}.drawio",
            ]
        else:
            raise SystemExit("Rendering the PNG needs draw.io desktop (or set DRAWIO_BIN) or a running Docker.")
        subprocess.run(command, check=True, capture_output=True)
        (OUT / f"{name}.png").write_bytes(_stamp_png((Path(tmp) / f"{name}.png").read_bytes(), _sha(drawio_text)))


def sync(png: str) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (model_yaml, drawio_text) in generate().items():
        for path, text in ((OUT / f"{name}.yaml", model_yaml), (OUT / f"{name}.drawio", drawio_text)):
            changed = not path.exists() or path.read_text() != text
            if changed:
                path.write_text(text)
            print(f"{'updated' if changed else 'unchanged'}: {path.relative_to(ROOT)}")
        png_path = OUT / f"{name}.png"
        if png_path.exists() and png_source_hash(png_path.read_bytes()) == _sha(drawio_text):
            print(f"unchanged: {png_path.relative_to(ROOT)}")
        elif png == "always" or (png == "auto" and can_render()):
            render_png(name, drawio_text)
            print(f"rendered: {png_path.relative_to(ROOT)}")
        else:
            print(f"stale: {png_path.relative_to(ROOT)} (needs draw.io or Docker; the docs-sync workflow renders it on PRs)")
    return 0


def check() -> int:
    stale = []
    for name, (model_yaml, drawio_text) in generate().items():
        for path, text in ((OUT / f"{name}.yaml", model_yaml), (OUT / f"{name}.drawio", drawio_text)):
            if not path.exists() or path.read_text() != text:
                stale.append(path.relative_to(ROOT).as_posix())
        png_path = OUT / f"{name}.png"
        if not png_path.exists() or png_source_hash(png_path.read_bytes()) != _sha(drawio_text):
            stale.append(png_path.relative_to(ROOT).as_posix())
    if stale:
        print("Architecture drift detected.\n")
        print("Generated architecture differs from committed architecture artifacts:")
        for path in stale:
            print(f"  - {path}")
        print("\nRun:\n\n  make architecture-sync\n")
        return 1
    print("Architecture artifacts are up to date.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.architecture")
    sub = parser.add_subparsers(dest="command", required=True)
    sync_parser = sub.add_parser("sync")
    sync_parser.add_argument(
        "--png",
        choices=("auto", "always", "never"),
        default="auto",
        help="render architecture.png with draw.io: auto = when draw.io or Docker is available",
    )
    sub.add_parser("check")
    sub.add_parser("facts")
    args = parser.parse_args(argv)
    try:
        if args.command == "sync":
            return sync(args.png)
        if args.command == "check":
            return check()
        print(json.dumps(discover(ROOT), indent=2, sort_keys=True))
        return 0
    except UnclassifiedError as error:
        print("Architecture discovery found evidence the catalog does not classify:\n")
        for item in error.items:
            print(f"  - {item}")
        print("\nClassify it in tools/architecture/catalog.yaml, then run `make architecture-sync`.")
        return 2


if __name__ == "__main__":
    sys.exit(main())
