version: 1
id: 26c20da5-8aff-5866-9024-ad70d4bf4db2
name: Remote AI Platform
slug: remote-ai-platform
protocol: http
port: 4500
scenarios:
  - name: default
    path: ./default.js
    default: true
    id: 9d4794cd-8e1d-5b81-bf05-513fe8a9ab81
